format: isaac_grasp
format_version: 1.0

object_frame: /mac_n_cheese_centered
gripper_frame: /Robotiq_2F_140_config/robotiq_base_link

grasps:
  "grasp_1":
    confidence: 1.0
    position:
      [-0.010495633731756123, 0.24758064725051476, -0.019003157563061073]
    orientation:
      {
        w: 0.7068147686383242,
        xyz: [0.706814636878625, 0.020321806926138813, 0.020321813210107037],
      }
    cspace_position:
      finger_joint: 0.033379483968019485
    pregrasp_cspace_position:
      finger_joint: 0.033379483968019485
