format: isaac_grasp
format_version: 1.0

object_frame: /gear_large
gripper_frame: /Robotiq_2F_85_main/robotiq_base_link

grasps:
   "grasp_0":
      confidence: 1.0
      position: [0.0015046894550323486, 0.0012550503015518188, 0.19957603842020038]
      orientation: {w: -1.3096739921146913e-10, xyz: [0.9999999999999999, 9.313224124593053e-10, -1.669104673918121e-08]}
      cspace_position:
         finger_joint: 0.033379748463630676
      pregrasp_cspace_position:
         finger_joint: 0.033379748463630676
