format: isaac_grasp
format_version: 1.0

object_frame: /soup_can
gripper_frame: /Robotiq_2F_85_main/Robotiq_2F_85

grasps:
   "grasp_0":
      confidence: 1.0
      position: [0.001654916653068919, 0.1647505458344229, -0.004605509245712995]
      orientation: {w:  0.014932713128151032, xyz: [-0.013793331075790782, -0.6955541469296506, 0.7181726859087803]}
      cspace_position:
         finger_joint: 0.1929556131362915
      pregrasp_cspace_position:
         finger_joint: 0.021975351497530937
        
   "grasp_1":
      confidence: 1.0
      position: [0.007119606453071853, 0.17180092180234294, 0.004782241231648584]
      orientation: {w: -0.016889992042875113, xyz: [0.01820498035214735, 0.7177648291786712, -0.6956255866867479]}
      cspace_position:
         finger_joint: 0.19534160196781158
      pregrasp_cspace_position:
         finger_joint: 0.02197553962469101

   "grasp_2":
      confidence: 1.0
      position: [-0.007972552243406022, 0.15955070261826496, -0.002637314668732531]
      orientation: {w: 0.7063360863570067, xyz: [0.7075895873407774, 0.010208081072793973, -0.00032261058028876244]}
      cspace_position:
         finger_joint: 0.18515841662883759
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

   "grasp_3":
      confidence: 1.0
      position: [-0.00576741081993208, 0.1555654241139062, 0.0008341574034137017]
      orientation: {w: 0.7063360863570067 , xyz: [0.7075895873407774, 0.010208081072793973, 0.00032261058028876244]}
      cspace_position:
         finger_joint: 0.18066702783107758
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

   "grasp_4":
      confidence: 1.0
      position: [-0.0018028488826523955, 0.15556347339967497, 0.004301127583157475]
      orientation: {w: 0.632387317689661 , xyz: [0.6377487988635527, 0.3148651557250173, -0.3064648163878394]}
      cspace_position:
         finger_joint: 0.16867877542972565
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

   "grasp_5":
      confidence: 1.0
      position: [-0.00434581375137358, 0.15552766443194777, -0.001282967550107218]
      orientation: {w: 0.6877004362636548, xyz: [0.6874630228560475, -0.15959989690882215, 0.1693770205048417]}
      cspace_position:
         finger_joint: 0.16794453561306
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

   "grasp_6":
      confidence: 1.0
      position: [-0.07545510924459699, 0.02146760079835464, -0.11248261402370821]
      orientation: {w: -0.0008190479087068492, xyz: [0.2906087351499088, 0.018038178618420775, 0.9565137285853109]}
      cspace_position:
         finger_joint: 0.18353310227394104
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

   "grasp_7":
      confidence: 1.0
      position: [-0.07553666228434053, 0.004476863360554257, -0.11268331928782498]
      orientation: {w: -0.012820428640903603, xyz: [0.2897954606152873, 0.013094107098256647, 0.9567553337298343]}
      cspace_position:
         finger_joint: 0.17921768128871918
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

   "grasp_8":
      confidence: 1.0
      position: [-0.07598881569602316, -0.004467448708516977, -0.11276758189896981]
      orientation: {w: -0.013922434360735758, xyz: [0.2908844080444205, 0.010788628881895357, 0.9564381993155213]}
      cspace_position:
         finger_joint: 0.17728741466999054
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

   "grasp_9":
      confidence: 1.0
      position: [0.11216014755429828, 0.025017647810875114, 0.06401888273660646]
      orientation: {w: -0.5049179508007715, xyz: [0.006051959086910752, 0.8628704354728962, 0.013185028711567737]}
      cspace_position:
         finger_joint: 0.1988285332918167
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

   "grasp_10":
      confidence: 1.0
      position: [0.1107251948126983, 0.008518560296572782, 0.066556969875668]
      orientation: {w: -0.4949751813073906, xyz: [0.006214027608263839, 0.868605002131114, 0.01357581188575463]}
      cspace_position:
         finger_joint: 0.1963425874710083
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

   "grasp_11":
      confidence: 1.0
      position: [0.11230295419156021, -0.009013825987638665, 0.06496697211905872]
      orientation: {w: -0.5019807298855646, xyz: [0.005416775799249651, 0.864561626931458, 0.01473754545633113]}
      cspace_position:
         finger_joint: 0.19329075515270233
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

   "grasp_12":
      confidence: 1.0
      position: [0.004957332906320152, -0.1544135657017725, 0.0057334575163264356]
      orientation: {w: -0.42148196917687497, xyz: [0.38706784074187156, 0.5831330324650572, 0.5763551880310576]}
      cspace_position:
         finger_joint: 0.1685638427734375
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

   "grasp_13":
      confidence: 1.0
      position: [0.007123925950684209, -0.1544134427802522, -0.0024426391157713763]
      orientation: {w: -0.7123072597158868, xyz: [0.6959365606261279, 0.07678143697063577, 0.04575240186748758]}
      cspace_position:
         finger_joint: 0.17714986205101013
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

   "grasp_14":
      confidence: 1.0
      position: [0.0036707425343152997, -0.1544133887972609, -0.0004085539399111144]
      orientation: {w: 0.6853144897913293, xyz: [-0.6802330382404549, 0.16529379974005304, 0.2000075586964284]}
      cspace_position:
         finger_joint: 0.16021937131881714
      pregrasp_cspace_position:
         finger_joint: 0.021957719698548317

